package com.librarysystem.model;

import java.time.LocalDateTime;

public class LogEntry {
    private int logId; // Auto-generated by database
    private LocalDateTime timestamp;
    private Integer userId; // Nullable if action is not user-specific (e.g. system event)
    private ActionType actionType;
    private String details; // e.g., ISBN of borrowed book, username for account creation

    public enum ActionType {
        BOOK_BORROW,
        BOOK_RETURN,
        LOGIN_SUCCESS,
        LOGIN_FAILURE, // Good to log for security monitoring
        ACCOUNT_CREATED,
        ACCOUNT_UPDATED, // e.g. password change
        ACCOUNT_DELETED,
        BOOK_ADDED,
        BOOK_UPDATED,
        BOOK_REMOVED,
        SYSTEM_ERROR,
        SYSTEM_STARTUP,
        SYSTEM_SHUTDOWN
    }

    public LogEntry(Integer userId, ActionType actionType, String details) {
        this.timestamp = LocalDateTime.now();
        this.userId = userId;
        this.actionType = actionType;
        this.details = details;
    }

    // Constructor for loading from DB
    public LogEntry(int logId, LocalDateTime timestamp, Integer userId, ActionType actionType, String details) {
        this.logId = logId;
        this.timestamp = timestamp;
        this.userId = userId;
        this.actionType = actionType;
        this.details = details;
    }

    // Getters
    public int getLogId() {
        return logId;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public Integer getUserId() {
        return userId;
    }

    public ActionType getActionType() {
        return actionType;
    }

    public String getDetails() {
        return details;
    }

    // Setters (logId and timestamp are typically not set manually after creation)
    public void setLogId(int logId) {
        this.logId = logId;
    }
     public void setTimestamp(LocalDateTime timestamp) { // For DB loading
        this.timestamp = timestamp;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public void setActionType(ActionType actionType) {
        this.actionType = actionType;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    @Override
    public String toString() {
        return "LogEntry{" +
                "logId=" + logId +
                ", timestamp=" + timestamp +
                ", userId=" + (userId != null ? userId : "N/A") +
                ", actionType=" + actionType +
                ", details='" + details + '\'' +
                '}';
    }
}
